# Profile thực nghiệm cục bộ; phải đổi sang URL HTTPS công khai trước bản đánh giá cuối.
issuing_address = myFN5aF1NpvPeyediipicfsvD2QGVU3D5M
verification_method = http://100.105.56.19:8088/api/blockcerts/issuers/kma/profile.json

chain = bitcoin_regtest
bitcoind

usb_name = /run/secrets/
key_file = pk_issuer.txt

unsigned_certificates_dir = /workspace/unsigned_certificates
signed_certificates_dir = /workspace/signed_certificates
blockchain_certificates_dir = /workspace/blockchain_certificates
work_dir = /workspace/work

no_safe_mode
batch_size = 10
issuance_timezone = UTC
